name: Auto Release Linux

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.2'
      
      - name: Generate tag
        id: tag
        run: echo "tag=v$(date +%Y%m%d)-$(printf "%02d" $(( ${GITHUB_RUN_NUMBER} % 100 )))" >> $GITHUB_OUTPUT
      
      - run: go mod download
      
      - name: Build
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 GOEXPERIMENT=jsonv2 go build -o build/v2node -trimpath -ldflags "-s -w"
      
      - run: cp README.md LICENSE build/
      
      - name: Download data files
        run: |
          curl -L https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat -o build/geoip.dat
          curl -L https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat -o build/geosite.dat
      
      - name: Package
        run: cd build && zip -r ../v2node-linux-64.zip .
      
      - name: Release
        uses: softprops/action-gh-release@v2.0.0
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          body: "Auto build\nCommit: ${{ github.sha }}"
          files: ./v2node-linux-64.zip
