name: Code Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  scan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.3'

      - name: Go Vet
        run: go vet ./...

      - name: Go Test
        run: go test ./... -v -timeout 60s -count=1

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: latest
          install-go: false

      - name: Gosec Security Scan
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -exclude=G104,G115,G117,G204,G301,G302,G304,G306,G103,G108,G112,G404 ./...
